version: '3.4'
services: 
    
    first-app:
        # build: .
        build: 
            context: .
            dockerfile: Dockerfile.dev
        ports: 
            - "4200:3001"
        volumes: 
            - /usr/src/app/node_modules
            - .:/usr/src/app

    # tests:
    #     build: 
    #         context: .
    #         dockerfile: Dockerfile
    #     volumes: 
    #         - /usr/src/app/node_modules
    #         - .:/usr/src/app
    #     command: ["npm", "run", "test"]

        
