# refer https://blog.tonysneed.com/2019/10/13/enable-ssl-with-asp-net-core-using-nginx-and-docker/

version: '3.4'
services: 
    reverseproxy:
        image: reverseproxy
        restart: always
        build: 
            context: ./nginx
            dockerfile: nginx.Dockerfile            
        ports: 
            - "3050:80"
        depends_on:
            - api
            - client
    api:
        image: api
        container_name: api
        build: 
            context: ./services/SimpleAPI
            dockerfile: simpleapi.Dockerfile   
        expose: 
            - "5000"     
    client:
        image: client
        container_name: client
        build:
            context: ./client 
            dockerfile: client.Dockerfile
        
        
        
                       