version: '3.4'

services: 

    redis-server:
        image: redis:alpine
        ports: 
            - "6379"
    node-app:
        restart: always
        build: .
        ports: 
            - "4001:8081"